ueckoken/KokenWiki

app/views/layouts/_navbar.html.erb

logged-in:
logged-in mobile:
logged-out:

GitHub-like navbar

---

app/views/pages/show.html.erb

[`relative-time`](https://github.com/github/time-elements#relative-time) is a part of [time-elements](https://github.com/github/time-elements).
`2019-12-20T19:00:00+09:00` -> `an hour ago`

use relative-time element

---

app/controllers/pages_controller.rb
app/views/pages/_left.html.erb
app/views/pages/_right.html.erb
app/views/pages/show.html.erb
db/migrate/20191225114344_update_root_page_path.rb
db/schema.rb

Christmas gift :gift: 
- use `Pathname` instead of pure string
- change the root page path `""` -> `"/"`

use Pathname instead of string

---

app/views/layouts/_footer.html.erb

smaller footer

---

app/assets/javascripts/cable.js
app/javascript/components/DiffViewer/index.jsx
app/javascript/components/Markdown.js
app/javascript/components/MdEditor/Editor.js
app/javascript/components/MdEditor/Markdown.js
app/javascript/components/MdEditor/MdEditor.js
app/javascript/components/MdEditor/index.js
app/javascript/components/MdEditor/redux.js
app/javascript/packs/application.js
app/javascript/packs/hello_react.jsx
app/javascript/packs/server_rendering.js
package.json
yarn.lock

use [prettier](https://prettier.io/) to format JavaScript files
run `yarn run prettier`

prettier code

---

app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb

fix missing markdown CSS in production mode

---

app/javascript/packs/application.js

fix missing Bootstrap JavaScript

---

app/controllers/pages_controller.rb
app/javascript/components/MdEditor/MdEditor.js
app/javascript/components/MdEditor/index.js
app/javascript/components/MdEditor/redux.js
app/models/page.rb
app/views/pages/show.html.erb
db/migrate/20200513184317_remove_is_public_from_pages.rb
db/schema.rb

BREAKING CHANGE:
Koken Wiki will be a closed wiki.

remove is_public from pages

---

yarn.lock

fix broken Bootstrap navbar toggler

---

app/javascript/components/Markdown.js
app/javascript/components/MdEditor/Editor.js
app/javascript/components/html-sanitizer-for-tui-editor.js
package.json
yarn.lock

Closes #85 
use `dompurify` to allow `<details>`, `<summary>`

fix unexpected HTML sanitization

---

Dockerfile

ref: https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions

use NodeSource

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
.dockerignore
config/database.yml
docker-compose.yaml

https://code.visualstudio.com/docs/remote/containers
https://code.visualstudio.com/docs/remote/create-dev-container
https://techbookfest.org/product/4696850535809024?productVariantID=5428870601768960

enable VSCode Dev Container

---

app.yaml

specify GAE instance class

---

app/controllers/files_controller.rb
app/controllers/pages_controller.rb
app/views/pages/show.html.erb
config/routes.rb

fix bad URI

---

app/controllers/application_controller.rb

fix template missing error for attached files

---

db/migrate/20210327184637_fix_mismatch_schema.rb
db/schema.rb

fix mismatch database schema

---

app/controllers/pages_controller.rb
app/models/page.rb
app/views/pages/show.html.erb

improve performance
reduce memory use

reduce mass SQL call

---

app/controllers/usergroups_controller.rb
app/models/usergroup.rb
app/views/layouts/application.html.erb
app/views/pages/_layout.html.erb
app/views/usergroups/edit.html.erb
app/views/usergroups/index.html.erb
app/views/usergroups/new.html.erb

- no implicit instance variable definition in controller
- editable name
- users count validation
- fix N+1
- error handling

refactor usergroup

---

app.yaml

full of memory, so often display 500 Error

change F2 instance_class

---

app/controllers/pages_controller.rb
app/models/page.rb

though I tried to use `change_column_default`, MySQL does not support default value for TEXT type

use `attribute` for default value

---

Gemfile
Gemfile.lock

Bump cancancan to 3.2 to support Rails 6.1

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/helpers/markdown_helper.rb
app/helpers/path_helper.rb
app/helpers/uri_helper.rb
app/models/page.rb
app/views/pages/search.html.erb
app/views/pages/show.html.erb

1. parse markdown in server side
1. get wiki internal links
1. show linked pages

add link card

---

app/javascript/components/Markdown.tsx

image lazyload enabled by default

---

app/models/page.rb
app/views/pages/_left.html.erb
app/views/pages/show.html.erb

find and show pages which has link the page

show backlinks

---

app/javascript/packs/application.scss

encourage users to follow HTML Living Standard

warn of use of deprecated HTML

---

package.json
yarn.lock

Bump @reduxjs/toolkit to 1.7.2

---

app/controllers/comments_controller.rb

fix invalid comment creation returns 500

---

app/javascript/react-integration.tsx

add webpack magic comment to generate no extra chunk in dynamic import

fix dynamic imports

---

app/javascript/components/MdEditor/MdEditor.tsx

OBに対応するために、ユーザーグループのデフォルトの名称の変更

change name from "部員全員" to "全員"

---

app/javascript/components/MdEditor/MdEditor.tsx

move editable group and readable group selector to over Markdown editor.

---

Gemfile
Gemfile.lock
app/helpers/any_time_helper.rb
app/helpers/time_elements_helper.rb
app/views/invitation_tokens/index.html.erb
app/views/pages/_right.html.erb
app/views/pages/_update-timestamp.html.erb
app/views/pages/show.html.erb
app/views/shared/_relative-time.html.erb
config/application.rb
config/initializers/time_formats.rb

- use `rails-i18n`, community-developed i18n config

date and time i18n

---

app.yaml

redirect to https

---

Dockerfile.dbmigrate

delete nodejs from migration

---

app/javascript/application.scss

toastuiのclassが変わっててcss当たってなかった

fix font not applied

---

Dockerfile.dbmigrate

Add trace option on migration
